// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("Domain.Entities.AppUser", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Address")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<int>("Age")
                .HasColumnType("int");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("nvarchar(450)");

            b.Property<string>("FullName")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Phone")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<int>("Role")
                .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique();

            b.ToTable("Users");
        });

        modelBuilder.Entity("Domain.Entities.Category", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("ImageUrl")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Categories");
        });

        modelBuilder.Entity("Domain.Entities.Order", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("PaymentId")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<int>("Status")
                .HasColumnType("int");

            b.Property<decimal>("TotalPrice")
                .HasColumnType("decimal(18,2)");

            b.Property<Guid>("UserId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.ToTable("Orders");
        });

        modelBuilder.Entity("Domain.Entities.OrderItem", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<Guid>("OrderId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("ProductId")
                .HasColumnType("uniqueidentifier");

            b.Property<int>("Quantity")
                .HasColumnType("int");

            b.Property<decimal>("UnitPrice")
                .HasColumnType("decimal(18,2)");

            b.HasKey("Id");

            b.HasIndex("OrderId");

            b.HasIndex("ProductId");

            b.ToTable("OrderItems");
        });

        modelBuilder.Entity("Domain.Entities.Product", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("CategoryId")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("MainImageUrl")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<decimal>("Price")
                .HasColumnType("decimal(18,2)");

            b.Property<int>("Status")
                .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("CategoryId");

            b.ToTable("Products");
        });

        modelBuilder.Entity("Domain.Entities.ProductImage", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("ImageUrl")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<Guid>("ProductId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("ProductId");

            b.ToTable("ProductImages");
        });

        modelBuilder.Entity("Domain.Entities.Order", b =>
        {
            b.HasOne("Domain.Entities.AppUser", "User")
                .WithMany("Orders")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("User");
        });

        modelBuilder.Entity("Domain.Entities.OrderItem", b =>
        {
            b.HasOne("Domain.Entities.Order", "Order")
                .WithMany("Items")
                .HasForeignKey("OrderId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Domain.Entities.Product", "Product")
                .WithMany()
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Order");

            b.Navigation("Product");
        });

        modelBuilder.Entity("Domain.Entities.Product", b =>
        {
            b.HasOne("Domain.Entities.Category", "Category")
                .WithMany("Products")
                .HasForeignKey("CategoryId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Category");
        });

        modelBuilder.Entity("Domain.Entities.ProductImage", b =>
        {
            b.HasOne("Domain.Entities.Product", "Product")
                .WithMany("Gallery")
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Product");
        });

        modelBuilder.Entity("Domain.Entities.AppUser", b =>
        {
            b.Navigation("Orders");
        });

        modelBuilder.Entity("Domain.Entities.Category", b =>
        {
            b.Navigation("Products");
        });

        modelBuilder.Entity("Domain.Entities.Order", b =>
        {
            b.Navigation("Items");
        });

        modelBuilder.Entity("Domain.Entities.Product", b =>
        {
            b.Navigation("Gallery");
        });
#pragma warning restore 612, 618
    }
}
